# Generated by Django 4.2.9 on 2024-01-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0005_sistema_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='s_partida',
            field=models.ManyToManyField(to='getdata.sistema_partida'),
        ),
    ]
