# Generated by Django 4.2.9 on 2024-01-24 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0007_alter_equipamientodiesel_qr_fabricante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamientodiesel',
            name='tipo',
        ),
        migrations.AddField(
            model_name='equipamientodiesel',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='getdata.tipo_equipamiento_diesel'),
            preserve_default=False,
        ),
    ]
