# Generated by Django 4.2.9 on 2024-01-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0009_setparams_ventilador_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='s_partida',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='s_partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='getdata.sistema_partida'),
            preserve_default=False,
        ),
    ]
