# Generated by Django 4.2.11 on 2024-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0012_proyecto_dis_e_sens_proyecto_potencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsdata',
            name='hr',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorsdata',
            name='tbh',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorsdata',
            name='tbs',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorsdata',
            name='tgbh',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
