# Generated by Django 4.2.11 on 2024-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0013_sensorsdata_hr_sensorsdata_tbh_sensorsdata_tbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ducto',
            name='f_fuga',
            field=models.FloatField(),
        ),
    ]
