--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Ubuntu 17.2-1.pgdg20.04+1)
-- Dumped by pg_dump version 17.4

-- Started on 2025-05-15 12:04:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 250 (class 1259 OID 16476)
-- Name: proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proyecto (
    id bigint NOT NULL,
    codos integer NOT NULL,
    caudal_requerido double precision NOT NULL,
    ancho_galeria double precision NOT NULL,
    alto_galeria double precision NOT NULL,
    area_galeria double precision NOT NULL,
    curva_diseno_id integer NOT NULL,
    ducto_id integer NOT NULL,
    ventilador_id integer NOT NULL,
    s_partida_id integer NOT NULL,
    factor double precision NOT NULL,
    dis_e_sens double precision NOT NULL,
    potencia double precision NOT NULL,
    lf double precision NOT NULL,
    nivel_carga character varying(12) NOT NULL,
    tipo_trabajo character varying(16) NOT NULL,
    dedf double precision NOT NULL
);


ALTER TABLE public.proyecto OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 16483)
-- Name: proyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3425 (class 0 OID 16476)
-- Dependencies: 250
-- Data for Name: proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proyecto (id, codos, caudal_requerido, ancho_galeria, alto_galeria, area_galeria, curva_diseno_id, ducto_id, ventilador_id, s_partida_id, factor, dis_e_sens, potencia, lf, nivel_carga, tipo_trabajo, dedf) FROM stdin;
2	3	120	5	5	20	4	2	1	1	80	70	120000	20	liviana	trabajo continuo	1
3	3	120	5	5	20	4	2	1	1	80	70	120000	20	liviana	75-25	1
4	3	262	12	15	54	4	8	5	1	30	44	25	14	pesada	trabajo continuo	5
\.


--
-- TOC entry 3432 (class 0 OID 0)
-- Dependencies: 253
-- Name: proyecto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proyecto_id_seq', 4, true);


--
-- TOC entry 3273 (class 2606 OID 16563)
-- Name: proyecto proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_pkey PRIMARY KEY (id);


--
-- TOC entry 3270 (class 1259 OID 16595)
-- Name: proyecto_curva_diseno_id_a2c8d5c0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX proyecto_curva_diseno_id_a2c8d5c0 ON public.proyecto USING btree (curva_diseno_id);


--
-- TOC entry 3271 (class 1259 OID 16596)
-- Name: proyecto_ducto_id_a813b12f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX proyecto_ducto_id_a813b12f ON public.proyecto USING btree (ducto_id);


--
-- TOC entry 3274 (class 1259 OID 16599)
-- Name: proyecto_s_partida_id_7fe84a4d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX proyecto_s_partida_id_7fe84a4d ON public.proyecto USING btree (s_partida_id);


--
-- TOC entry 3275 (class 1259 OID 16600)
-- Name: proyecto_ventilador_id_b9050be5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX proyecto_ventilador_id_b9050be5 ON public.proyecto USING btree (ventilador_id);


--
-- TOC entry 3276 (class 2606 OID 16668)
-- Name: proyecto proyecto_curva_diseno_id_a2c8d5c0_fk_curva_diseno_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_curva_diseno_id_a2c8d5c0_fk_curva_diseno_id FOREIGN KEY (curva_diseno_id) REFERENCES public.curva_diseno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3277 (class 2606 OID 16673)
-- Name: proyecto proyecto_ducto_id_a813b12f_fk_ducto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_ducto_id_a813b12f_fk_ducto_id FOREIGN KEY (ducto_id) REFERENCES public.ducto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3278 (class 2606 OID 16688)
-- Name: proyecto proyecto_s_partida_id_7fe84a4d_fk_getdata_sistema_partida_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_s_partida_id_7fe84a4d_fk_getdata_sistema_partida_id FOREIGN KEY (s_partida_id) REFERENCES public.getdata_sistema_partida(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3279 (class 2606 OID 16693)
-- Name: proyecto proyecto_ventilador_id_b9050be5_fk_ventilador_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_ventilador_id_b9050be5_fk_ventilador_id FOREIGN KEY (ventilador_id) REFERENCES public.ventilador(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-05-15 12:04:22

--
-- PostgreSQL database dump complete
--

