# Generated by Django 4.2.9 on 2024-01-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurvaDiseno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('angulo', models.FloatField()),
                ('rpm', models.FloatField()),
                ('densidad', models.FloatField()),
                ('datos_curva', models.JSONField()),
            ],
            options={
                'db_table': 'curva_diseno',
            },
        ),
        migrations.CreateModel(
            name='Ducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f_friccion', models.FloatField()),
                ('f_fuga', models.TextField()),
                ('tipo', models.TextField()),
                ('largo', models.FloatField()),
            ],
            options={
                'db_table': 'ducto',
            },
        ),
        migrations.CreateModel(
            name='EquipamientoDiesel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('modelo_diesel', models.TextField()),
                ('potencia', models.FloatField()),
                ('qr_fabricante', models.FloatField()),
                ('qr_calculado', models.FloatField()),
            ],
            options={
                'db_table': 'equipamiento_diesel',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('pt2', models.FloatField()),
                ('ps2', models.FloatField()),
                ('densidad2', models.FloatField()),
                ('q2', models.FloatField()),
                ('pt1', models.FloatField()),
                ('ps1', models.FloatField()),
                ('densidad1', models.FloatField()),
                ('q1', models.FloatField()),
                ('lc', models.FloatField()),
                ('qf', models.FloatField()),
                ('k', models.FloatField()),
            ],
            options={
                'db_table': 'sensors_data',
            },
        ),
        migrations.CreateModel(
            name='VdfData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('fref', models.FloatField()),
                ('freal', models.FloatField()),
                ('vf', models.FloatField()),
                ('oc', models.FloatField(db_column='if')),
                ('power', models.FloatField()),
                ('powerc', models.FloatField()),
                ('rpm', models.FloatField()),
            ],
            options={
                'db_table': 'vdf_data',
            },
        ),
        migrations.CreateModel(
            name='Ventilador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField()),
                ('vmm', models.FloatField()),
                ('amm', models.FloatField()),
                ('rmm', models.FloatField()),
                ('polos', models.IntegerField()),
                ('accesorios', models.CharField()),
            ],
            options={
                'db_table': 'ventilador',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codos', models.IntegerField()),
                ('caudal_requerido', models.FloatField()),
                ('ancho_galeria', models.FloatField()),
                ('alto_galeria', models.FloatField()),
                ('area_galeria', models.FloatField()),
                ('curva_diseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.curvadiseno')),
                ('ducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.ducto')),
                ('equipamientos', models.ManyToManyField(to='getdata.equipamientodiesel')),
                ('ventilador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.ventilador')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
        migrations.AddField(
            model_name='curvadiseno',
            name='ventilador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdata.ventilador'),
        ),
    ]
