# Generated by Django 4.2.9 on 2024-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_remove_ducto_tipo_ducto_t_acople_ducto_t_ducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas_Ventilador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Equipamiento_Diesel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='equipamientodiesel',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='ventilador',
            name='accesorios',
        ),
        migrations.AddField(
            model_name='equipamientodiesel',
            name='tipo',
            field=models.ManyToManyField(to='getdata.tipo_equipamiento_diesel'),
        ),
        migrations.AddField(
            model_name='ventilador',
            name='accesorios',
            field=models.ManyToManyField(to='getdata.caracteristicas_ventilador'),
        ),
    ]
