# Generated by Django 4.2.9 on 2024-01-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0004_curvadiseno_idu_ducto_idu_equipamientodiesel_idu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema_Partida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
            ],
        ),
    ]
