# Generated by Django 4.2.9 on 2024-01-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0006_proyecto_s_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamientodiesel',
            name='qr_fabricante',
            field=models.FloatField(null=True),
        ),
    ]
