# Generated by Django 4.2.9 on 2024-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0008_remove_equipamientodiesel_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetParams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('fref', models.FloatField()),
            ],
            options={
                'db_table': 'set_params',
            },
        ),
        migrations.AddField(
            model_name='ventilador',
            name='hp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
