# Generated by Django 4.2.9 on 2024-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0010_remove_proyecto_s_partida_proyecto_s_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='factor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
