# Generated by Django 4.2.11 on 2024-10-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0015_caracteristicas_ventilador_perdida_choque'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='img_ventilador',
            field=models.ImageField(default='ventilador/vent-def.jpg', upload_to='ventilador/'),
        ),
    ]
