# Generated by Django 4.2.11 on 2024-10-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0016_proyecto_img_ventilador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='img_ventilador',
        ),
        migrations.AddField(
            model_name='ventilador',
            name='img_ventilador',
            field=models.ImageField(default='ventilador/vent-def.jpg', upload_to='ventilador/'),
        ),
    ]
