# Generated by Django 4.2.11 on 2024-10-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0017_remove_proyecto_img_ventilador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristicas_ventilador',
            old_name='perdida_choque',
            new_name='factor_choque',
        ),
    ]
