# Generated by Django 4.2.11 on 2024-10-28 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0019_ducto_area_ducto_diametro_alter_ducto_t_ducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='lf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semaforo', models.IntegerField()),
                ('sensor_ahora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor_ahora', to='getdata.sensorsdata')),
                ('sensor_hace30m', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor_hace30m', to='getdata.sensorsdata')),
            ],
            options={
                'db_table': 'evento',
            },
        ),
    ]
