# Generated by Django 4.2.11 on 2024-11-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0021_proyecto_nivel_carga_proyecto_tipo_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas_ventilador',
            name='factor_choque',
            field=models.FloatField(),
        ),
    ]
