# Generated by Django 4.2.11 on 2024-11-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0022_alter_caracteristicas_ventilador_factor_choque'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicas_ventilador',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
