# Generated by Django 4.2.11 on 2024-11-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0023_caracteristicas_ventilador_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventilador',
            old_name='rmm',
            new_name='nmm',
        ),
    ]
