# Generated by Django 4.2.11 on 2025-01-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0024_rename_rmm_ventilador_nmm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducto',
            name='Ldsf',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='densidad1',
            field=models.FloatField(verbose_name='Pesión estática sensor 1 (Pa)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='densidad2',
            field=models.FloatField(verbose_name='Presión barométrica sensor 2 (Pa)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='hr',
            field=models.FloatField(verbose_name='humedad relativa'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='k',
            field=models.FloatField(verbose_name='factor de fricción'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='lc',
            field=models.FloatField(verbose_name='Temperatura seca sensor 2 (°C)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='ps1',
            field=models.FloatField(verbose_name='Presión total sensor 1 (Pa)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='ps2',
            field=models.FloatField(verbose_name='Presión estática sensor 2 (Pa)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='pt1',
            field=models.FloatField(verbose_name='Humedad Relativa sensor 2 (%)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='pt2',
            field=models.FloatField(verbose_name='Presión total sensor 2 (Pa)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='q1',
            field=models.FloatField(verbose_name='Presión barométrica sensor 1 (Pa)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='q2',
            field=models.FloatField(verbose_name='Temperatura seca sensor 2 (°C)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='qf',
            field=models.FloatField(verbose_name='Humedad Relativa sensor 1 (%)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='tbs',
            field=models.FloatField(verbose_name='temperatura seca'),
        ),
    ]
