# Generated by Django 4.2.11 on 2025-02-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0025_ducto_ldsf_alter_sensordata_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorsdata',
            old_name='qf',
            new_name='HRs1',
        ),
        migrations.RenameField(
            model_name='sensorsdata',
            old_name='q1',
            new_name='Pbs1',
        ),
        migrations.RenameField(
            model_name='sensorsdata',
            old_name='densidad2',
            new_name='Pbs2',
        ),
        migrations.RenameField(
            model_name='sensorsdata',
            old_name='lc',
            new_name='Tbs1',
        ),
        migrations.RenameField(
            model_name='sensorsdata',
            old_name='q2',
            new_name='Tbs2',
        ),
        migrations.RemoveField(
            model_name='sensorsdata',
            name='densidad1',
        ),
        migrations.AddField(
            model_name='sensorsdata',
            name='HRs2',
            field=models.FloatField(default=1, verbose_name='Humedad Relativa sensor 2 (%)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='ps1',
            field=models.FloatField(verbose_name='Pesión estática sensor 1 (Pa)'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='pt1',
            field=models.FloatField(verbose_name='Presión total sensor 1 (Pa)'),
        ),
    ]
