# Generated by Django 4.2.11 on 2025-02-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0026_rename_qf_sensorsdata_hrs1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducto',
            name='dS2_F',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ducto',
            name='dSensores',
            field=models.FloatField(default=0),
        ),
    ]
