# Generated by Django 4.2.11 on 2025-02-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0027_ducto_ds2_f_ducto_dsensores'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='dedf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
