# Generated by Django 4.2.11 on 2025-03-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0028_proyecto_dedf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('insert_interval', models.IntegerField(default=60, help_text='Intervalo en segundos para insertar nuevos valores')),
            ],
        ),
    ]
