# Generated by Django 4.2.11 on 2025-03-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0029_simulador'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulador',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
