# Generated by Django 4.2.11 on 2025-03-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0030_simulador_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perdida_choque_total', models.JSONField(blank=True, null=True)),
                ('perdida_choque_codos', models.JSONField(blank=True, null=True)),
                ('perdida_accesorios_ventilador', models.JSONField(blank=True, null=True)),
                ('perdida_choque_salida', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.AlterModelTable(
            name='simulador',
            table='simulador',
        ),
    ]
