# Generated by Django 4.2.11 on 2025-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0031_historial_alter_simulador_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='perdida_accesorios_ventilador',
            new_name='f1',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='perdida_choque_codos',
            new_name='f2_dc',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='perdida_choque_salida',
            new_name='f2_do',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='perdida_choque_total',
            new_name='pc1_dc',
        ),
        migrations.AddField(
            model_name='historial',
            name='pc2_dc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pc345_dc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pcc_dc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pcs_dc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pct_sys',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pd_e',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pd_v',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pta_v',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='q1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='q_c1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='q_c2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='q_c345',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='qf',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
