# Generated by Django 4.2.11 on 2025-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0032_rename_perdida_accesorios_ventilador_historial_f1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='intervalo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
