# Generated by Django 4.2.11 on 2025-03-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0033_historial_intervalo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='intervalo',
        ),
        migrations.AddField(
            model_name='historial',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='f1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='f2_dc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='f2_do',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pc1_dc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pc2_dc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pc345_dc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pcc_dc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pcs_dc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pct_sys',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pd_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pd_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pta_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='q1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='q_c1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='q_c2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='q_c345',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='qf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
