# Generated by Django 4.2.11 on 2025-04-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0034_remove_historial_intervalo_historial_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='pe_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='tbh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='tbs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
