# Generated by Django 4.2.11 on 2025-04-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0035_historial_pe_v_historial_tbh_historial_tbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='presion_t',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
