# Generated by Django 4.2.11 on 2025-04-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0036_historial_presion_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='lc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='tgbh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
