# Generated by Django 4.2.11 on 2025-04-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0037_historial_lc_historial_tgbh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='f1',
            field=models.FloatField(blank=True, null=True, verbose_name='fórmula parte 1'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='f2_dc',
            field=models.FloatField(blank=True, null=True, verbose_name='fórmula parte 2 ducto circular'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='f2_do',
            field=models.FloatField(blank=True, null=True, verbose_name='fórmula parte 2 ducto ovalado'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='lc',
            field=models.FloatField(blank=True, null=True, verbose_name='temperatura seca sensor 1 (°C)'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pc1_dc',
            field=models.FloatField(blank=True, null=True, verbose_name='pérdida codo 1 ducto circular'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pc2_dc',
            field=models.FloatField(blank=True, null=True, verbose_name='pérdida codo 2 ducto circular'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pc345_dc',
            field=models.FloatField(blank=True, null=True, verbose_name='pérdida codos 3,4,5 ducto circular'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pcc_dc',
            field=models.FloatField(blank=True, null=True, verbose_name='pérdida choque codos ducto'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pcs_dc',
            field=models.FloatField(blank=True, null=True, verbose_name='pérdida choque salida ducto'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pct_sys',
            field=models.FloatField(blank=True, null=True, verbose_name='pérdida choque total sistema ducto circular/ovalado'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pd_e',
            field=models.FloatField(blank=True, null=True, verbose_name='presión dinámica entrada'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pd_v',
            field=models.FloatField(blank=True, null=True, verbose_name='presión dinámica ventilador'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pe_v',
            field=models.FloatField(blank=True, null=True, verbose_name='presión estática ventilador'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='presion_t',
            field=models.FloatField(blank=True, null=True, verbose_name='presión total'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pta_v',
            field=models.FloatField(blank=True, null=True, verbose_name='pérdida total accesorios ventilador'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='q1',
            field=models.FloatField(blank=True, null=True, verbose_name='Q1'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='q_c1',
            field=models.FloatField(blank=True, null=True, verbose_name='Q codo 1'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='q_c2',
            field=models.FloatField(blank=True, null=True, verbose_name='Q codo 2'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='q_c345',
            field=models.FloatField(blank=True, null=True, verbose_name='Q codos 3,4,5'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='qf',
            field=models.FloatField(blank=True, null=True, verbose_name='Qf'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tbh',
            field=models.FloatField(blank=True, null=True, verbose_name='temperatura bulbo húmedo'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tbs',
            field=models.FloatField(blank=True, null=True, verbose_name='temperatura bulbo seco'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tgbh',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historial',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro'),
        ),
    ]
