# Generated by Django 4.2.11 on 2025-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0038_alter_historial_f1_alter_historial_f2_dc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalosDeActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaforo', models.IntegerField(blank=True, null=True)),
                ('estado_semaforo', models.BooleanField(default=True)),
                ('sistema', models.IntegerField(blank=True, null=True)),
                ('estado_sistema', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historial',
            name='lc',
            field=models.FloatField(blank=True, null=True, verbose_name='temperatura seca sensor'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='q1',
            field=models.FloatField(blank=True, null=True, verbose_name='Caudal Q1'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='qf',
            field=models.FloatField(blank=True, null=True, verbose_name='Caudal de la frente'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tgbh',
            field=models.FloatField(blank=True, null=True, verbose_name='tgbh'),
        ),
    ]
