# Generated by Django 4.2.11 on 2025-04-30 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getdata", "0039_intervalosdeactualizacion_alter_historial_lc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historial",
            name="creado_en",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 30, 18, 36, 6, 46704),
                verbose_name="fecha y hora de registro",
            ),
        ),
    ]
