# Generated by Django 4.2.11 on 2025-05-14 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("getdata", "0040_historial_creado_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="creado_en",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="fecha y hora de registro",
            ),
        ),
    ]
