# Generated by Django 4.2.11 on 2025-05-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getdata", "0041_alter_historial_creado_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorsdata",
            name="hr",
            field=models.FloatField(
                blank=True, null=True, verbose_name="humedad relativa"
            ),
        ),
        migrations.AlterField(
            model_name="sensorsdata",
            name="k",
            field=models.FloatField(
                blank=True, null=True, verbose_name="factor de fricción"
            ),
        ),
        migrations.AlterField(
            model_name="sensorsdata",
            name="tbh",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensorsdata",
            name="tbs",
            field=models.FloatField(
                blank=True, null=True, verbose_name="temperatura seca"
            ),
        ),
        migrations.AlterField(
            model_name="sensorsdata",
            name="tgbh",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
