# Generated by Django 4.2.11 on 2025-05-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FugasConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="Configuración general", max_length=100),
                ),
                (
                    "presion_promedio",
                    models.FloatField(
                        help_text="Promedio de presión normal del sistema (en pt1)"
                    ),
                ),
                (
                    "tolerancia_minima",
                    models.FloatField(
                        help_text="Porcentaje mínimo tolerado de caída (ej. 0.05 = 5%)"
                    ),
                ),
                (
                    "tolerancia_maxima",
                    models.FloatField(
                        help_text="Porcentaje máximo tolerado (ej. 0.2 = 20%)"
                    ),
                ),
                ("alerta_activa", models.BooleanField(default=True)),
                ("sistema_bloqueado", models.BooleanField(default=False)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SemaforoEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="Semáforo General", max_length=100),
                ),
                (
                    "color_actual",
                    models.CharField(
                        choices=[
                            ("verde", "Verde"),
                            ("amarillo", "Amarillo"),
                            ("rojo", "Rojo"),
                        ],
                        default="verde",
                        max_length=10,
                    ),
                ),
                ("esta_bloqueado", models.BooleanField(default=False)),
                ("motivo_bloqueo", models.TextField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
