# Generated by Django 4.2.11 on 2025-05-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fugasconfig",
            name="tolerancia_maxima",
            field=models.FloatField(
                help_text="Porcentaje máximo tolerado (ej. 5 = 5%)"
            ),
        ),
        migrations.AlterField(
            model_name="fugasconfig",
            name="tolerancia_minima",
            field=models.FloatField(
                help_text="Porcentaje mínimo tolerado de caída (ej. 5 = 5%)"
            ),
        ),
    ]
