# Generated by Django 4.2.11 on 2025-05-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraficoTolerancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("total_pressure", "Presión total"),
                            ("static_pressure", "Presión estática"),
                            ("power", "Potencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tolerancia",
                    models.CharField(
                        choices=[
                            ("AN1", "AN1"),
                            ("AN2", "AN2"),
                            ("AN3", "AN3"),
                            ("AN4", "AN4"),
                        ],
                        default="AN3",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "db_table": "graficotolerancia",
            },
        ),
    ]
