# Generated by Django 4.2.11 on 2025-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fandesign", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graficotolerancia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("total_pressure", "Presión total"),
                    ("static_pressure", "Presión estática"),
                    ("power", "Potencia"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
